# Generated by Django 5.2.10 on 2026-02-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
